/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { AlchemyGame } from "./AlchemyGame";
export type { AlchemyGameHelper } from "./AlchemyGameHelper";
export type { NFTStake } from "./NFTStake";
export type { NFTStakeHelper } from "./NFTStakeHelper";
